name: Compile and test

on: [pull_request]

jobs:
  macos:
    name: macos
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Switch Xcode version
      run: sudo xcode-select -s /Applications/Xcode_11.4.1.app/Contents/Developer
    - name: Run tests
      run: swift test
